# [作業目標]

1. [簡答題] 請問下列四種不同的 DataFrame 選取結果有什麼差異？

```
df.loc[ '2013-01-01', 'A'] 
df.loc[ '2013-01-01', ['A', 'B'] ] 
df.loc[ '2013-01-01':'2013-01-02', 'A' ] 
df.loc[ '2013-01-01':'2013-01-05', 'A':'C'] 
```


2. 請根據提供的資料，選擇出下列的要求：

```
# - select the first 3 rows.
# - select the odd rows. (index = 1, 3, 5)
# - select the last 2 columns.
# - select the even columns. (index = 0, 2, 4)
```

3. 請根據提供的資料，選擇出下列的要求：

```
# - 1. filtered by first column > 20?
# - 2. filtered by first column + second column > 50
# - 3. filtered by first column < 30 or second column > 30
# - 4. filtered by total sum of row > 100
```

# 作業

### 1. [簡答題] 請問下列四種不同的 DataFrame 選取結果有什麼差異？

```
df.loc[ '2013-01-01', 'A'] 
df.loc[ '2013-01-01', ['A', 'B'] ] 
df.loc[ '2013-01-01':'2013-01-02', 'A' ] 
df.loc[ '2013-01-01':'2013-01-05', 'A':'C'] 
```

df.loc[ '2013-01-01', 'A'] : 選取row: 2013-01-01、column: A  
df.loc[ '2013-01-01', ['A', 'B'] ]'] : 選取row: 2013-01-01、column: A, B   
df.loc[ '2013-01-01':'2013-01-02', 'A' ]'] : 選取row: 2013-01-01到2013-01-02、column: A   
df.loc[ '2013-01-01':'2013-01-05', 'A':'C'] : 選取row: 2013-01-01到2013-01-05、column: A, C

### 2. 請根據提供的資料，選擇出下列的要求：

```
# - select the first 3 rows.
# - select the odd rows. (index = 1, 3, 5)
# - select the last 2 columns.
# - select the even rows. (index = 0, 2, 4)
```

In [1]:
import pandas as pd
import numpy as np

In [2]:
df = pd.DataFrame(np.random.randn(6,3),columns=['col1','col2','col3'])
df

       col1      col2      col3
0  0.813577 -0.689770  1.609707
1  1.486024 -1.014634  0.031219
2  0.313839  0.255078  0.498058
3 -0.079468 -1.515885 -0.420605
4  0.275931 -0.591113  0.480400
5  0.606217  0.090309  1.385948

In [ ]:
df.iloc[0:3]

       col1      col2      col3
0  1.036569 -1.456640  0.294391
1  0.679412  0.834119  0.482463
2 -0.834688  0.356212  0.108426

In [3]:
#df.iloc[1: len(df): 2]
df.iloc[1:: 2]

       col1      col2      col3
1  1.486024 -1.014634  0.031219
3 -0.079468 -1.515885 -0.420605
5  0.606217  0.090309  1.385948

In [6]:
#df.iloc[:,[len(df.iloc[0])-2, len(df.iloc[0])-1]]
df.iloc[:,-2:]

       col2      col3
0 -0.689770  1.609707
1 -1.014634  0.031219
2  0.255078  0.498058
3 -1.515885 -0.420605
4 -0.591113  0.480400
5  0.090309  1.385948

In [9]:
#df.iloc[0: len(df): 2]
df.iloc[0:: 2]

       col1      col2      col3
0  0.813577 -0.689770  1.609707
2  0.313839  0.255078  0.498058
4  0.275931 -0.591113  0.480400

### 3. 請根據提供的資料，選擇出下列的要求：

```
# - 1. filtered by first column > 20?
# - 2. filtered by first column + second column > 50
# - 3. filtered by first column < 30 or second column > 30
# - 4. filtered by total sum of row > 100
```

In [11]:
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
df

     0   1   2   3
0   13  15  35  33
1   36  25  21  18
2   30  29  17  19
3   38  36  29  18
4   38  10  14  15
5   17  34  37  27
6   13  11  31  10
7   36  20  28  38
8   21  19  31  12
9   15  29  29  39
10  11  22  38  13
11  37  17  36  27
12  34  36  31  21
13  33  35  10  20
14  36  21  19  10

In [ ]:
df[df[0] > 20]

     0   1   2   3
0   32  26  14  38
1   25  21  22  32
2   39  29  27  31
3   31  38  23  27
4   25  10  26  12
5   37  32  32  37
7   21  27  24  10
8   22  37  21  23
9   32  32  20  15
11  24  29  31  24
12  34  14  13  16
13  38  29  37  27
14  36  39  32  14

In [ ]:
df[df[0] + df[1] > 50]

     0   1   2   3
0   32  26  14  38
2   39  29  27  31
3   31  38  23  27
5   37  32  32  37
8   22  37  21  23
9   32  32  20  15
11  24  29  31  24
13  38  29  37  27
14  36  39  32  14

In [12]:
df[(df[0]<30) | (df[1]>30)]

     0   1   2   3
0   13  15  35  33
3   38  36  29  18
5   17  34  37  27
6   13  11  31  10
8   21  19  31  12
9   15  29  29  39
10  11  22  38  13
12  34  36  31  21
13  33  35  10  20

In [ ]:
df[df.sum(axis=1) > 100]

     0   1   2   3
0   32  26  14  38
2   39  29  27  31
3   31  38  23  27
5   37  32  32  37
8   22  37  21  23
11  24  29  31  24
13  38  29  37  27
14  36  39  32  14