# [作業目標]

1. [簡答題] 請問下列四種不同的 DataFrame 選取結果有什麼差異？

```
df.loc[ '2013-01-01', 'A'] 
df.loc[ '2013-01-01', ['A', 'B'] ] 
df.loc[ '2013-01-01':'2013-01-02', 'A' ] 
df.loc[ '2013-01-01':'2013-01-05', 'A':'C'] 
```


2. 請根據提供的資料，選擇出下列的要求：

```
# - select the first 3 rows.
# - select the odd rows. (index = 1, 3, 5)
# - select the last 2 columns.
# - select the even columns. (index = 0, 2, 4)
```

3. 請根據提供的資料，選擇出下列的要求：

```
# - 1. filtered by first column > 20?
# - 2. filtered by first column + second column > 50
# - 3. filtered by first column < 30 or second column > 30
# - 4. filtered by total sum of row > 100
```

# 作業

### 1. [簡答題] 請問下列四種不同的 DataFrame 選取結果有什麼差異？

```
df.loc[ '2013-01-01', 'A'] 
df.loc[ '2013-01-01', ['A', 'B'] ] 
df.loc[ '2013-01-01':'2013-01-02', 'A' ] 
df.loc[ '2013-01-01':'2013-01-05', 'A':'C'] 
```

df.loc[ '2013-01-01', 'A'] : 選取row: 2013-01-01、column: A  
df.loc[ '2013-01-01', ['A', 'B'] ]'] : 選取row: 2013-01-01、column: A, B   
df.loc[ '2013-01-01':'2013-01-02', 'A' ]'] : 選取row: 2013-01-01到2013-01-02、column: A   
df.loc[ '2013-01-01':'2013-01-05', 'A':'C'] : 選取row: 2013-01-01到2013-01-05、column: A, C

### 2. 請根據提供的資料，選擇出下列的要求：

```
# - select the first 3 rows.
# - select the odd rows. (index = 1, 3, 5)
# - select the last 2 columns.
# - select the even rows. (index = 0, 2, 4)
```

In [7]:
import pandas as pd
import numpy as np

In [8]:
df = pd.DataFrame(np.random.randn(6,3),columns=['col1','col2','col3'])
df

       col1      col2      col3
0  1.036569 -1.456640  0.294391
1  0.679412  0.834119  0.482463
2 -0.834688  0.356212  0.108426
3  0.181715  0.680827  0.292932
4  0.410148 -0.786372  0.803674
5 -0.467070 -0.303058 -0.227049

In [12]:
df.iloc[0:3]

       col1      col2      col3
0  1.036569 -1.456640  0.294391
1  0.679412  0.834119  0.482463
2 -0.834688  0.356212  0.108426

In [19]:
df.iloc[1: len(df): 2]

       col1      col2      col3
1  0.679412  0.834119  0.482463
3  0.181715  0.680827  0.292932
5 -0.467070 -0.303058 -0.227049

In [59]:
df.iloc[:,[len(df.iloc[0])-2, len(df.iloc[0])-1]]

       col2      col3
0 -1.456640  0.294391
1  0.834119  0.482463
2  0.356212  0.108426
3  0.680827  0.292932
4 -0.786372  0.803674
5 -0.303058 -0.227049

In [62]:
df.iloc[0: len(df): 2]

       col1      col2      col3
0  1.036569 -1.456640  0.294391
2 -0.834688  0.356212  0.108426
4  0.410148 -0.786372  0.803674

### 3. 請根據提供的資料，選擇出下列的要求：

```
# - 1. filtered by first column > 20?
# - 2. filtered by first column + second column > 50
# - 3. filtered by first column < 30 or second column > 30
# - 4. filtered by total sum of row > 100
```

In [63]:
df = pd.DataFrame(np.random.randint(10, 40, 60).reshape(-1, 4))
df

     0   1   2   3
0   32  26  14  38
1   25  21  22  32
2   39  29  27  31
3   31  38  23  27
4   25  10  26  12
5   37  32  32  37
6   13  14  24  25
7   21  27  24  10
8   22  37  21  23
9   32  32  20  15
10  16  22  13  19
11  24  29  31  24
12  34  14  13  16
13  38  29  37  27
14  36  39  32  14

In [65]:
df[df[0] > 20]

     0   1   2   3
0   32  26  14  38
1   25  21  22  32
2   39  29  27  31
3   31  38  23  27
4   25  10  26  12
5   37  32  32  37
7   21  27  24  10
8   22  37  21  23
9   32  32  20  15
11  24  29  31  24
12  34  14  13  16
13  38  29  37  27
14  36  39  32  14

In [66]:
df[df[0] + df[1] > 50]

     0   1   2   3
0   32  26  14  38
2   39  29  27  31
3   31  38  23  27
5   37  32  32  37
8   22  37  21  23
9   32  32  20  15
11  24  29  31  24
13  38  29  37  27
14  36  39  32  14

In [71]:
df[(df[0]<30)&(df[1]>30)]

    0   1   2   3
8  22  37  21  23

In [83]:
df[df.sum(axis=1) > 100]

     0   1   2   3
0   32  26  14  38
2   39  29  27  31
3   31  38  23  27
5   37  32  32  37
8   22  37  21  23
11  24  29  31  24
13  38  29  37  27
14  36  39  32  14